# Generated by Django 4.2.3 on 2023-09-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='clinicaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentname', models.CharField(choices=[('hw', 'height/weight'), ('bp', 'blood pressure'), ('hr', 'heartrate')], max_length=20)),
                ('componentvalue', models.CharField(max_length=20)),
                ('measureddate', models.DateField(auto_now_add=True)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalapp.patient')),
            ],
        ),
    ]
